spring:
  datasource:
    url: jdbc:postgresql://db:5432/trello_clone
    username: trello_clone_user
    password: trello_clone_user_password
  jpa:
    open-in-view: false

server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
